FizzBuzz/Models/FizzBuzzResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzBuzz.Models
{
    public class FizzBuzzResult
    {
        [Display(Name = "Results from your entry")]
        public string FizzBuzzRes { get; set; }

        public string FontColor { get; set; }
    }
}

FizzBuzz/Models/UserInput.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzBuzz.Models
{
    public class UserInput
    {
        [Range(1, 1000)]
        [Display(Name = "Number")]
        public int UserEntry { get; set; }
    }
}

FizzBuzz/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FizzBuzz.Models;

namespace FizzBuzz.Controllers
{
    public class FizzBuzzController : Controller
    {
  
        public ActionResult Index([Bind(Include = "UserEntry")] UserInput userInput)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Results", new { input = userInput.UserEntry});
            }

            return View(userInput);
        }

        public ActionResult Results(int? input)
        {
            if (input != null)
            {
                var fizzBuzzResultAsString = GetResultsWithFizzBuzz((int) input, DateTime.Now.DayOfWeek);
                var fizzBuzzResults = new List<FizzBuzzResult>();
                foreach (var returnedString in fizzBuzzResultAsString)
                {
                    var fb = new FizzBuzzResult {FizzBuzzRes = returnedString};

                    switch (returnedString)
                    {
                        case "Fizz":
                            fb.FontColor = "Blue";
                            break;
                        case "Buzz":
                            fb.FontColor = "Green";
                            break;
                        default:
                            fb.FontColor = "Black";
                            break;
                    }

                    fizzBuzzResults.Add(fb);

                }

                return View(fizzBuzzResults);
            }
            return RedirectToAction("Index");
        }

        public List<string> GetResultsWithFizzBuzz(int userEntry, DayOfWeek dayOfWeek)
        { 
            var fizzBuzzList = new List<string>();

            for (var i = 1; i <= userEntry; i++)
            {
                fizzBuzzList.Add(GetNextFizzBuzzResult(i, dayOfWeek));
            }
            return fizzBuzzList;
        }

        private string GetNextFizzBuzzResult(int position, DayOfWeek dayOfWeek)
        {
            var randomWord1 = "Fizz";
            var randomWord2 = "Buzz";

            if (dayOfWeek == DayOfWeek.Wednesday)
            {
                randomWord1 = "Wizz";
                randomWord2 = "Wuzz";
            }


            if (position % 15 == 0)
            {
                return (randomWord1 + " " + randomWord2);
            }
            if (position % 3 == 0)
            {
                return (randomWord1);
            }
            if (position % 5 == 0)
            {
                return (randomWord2);
            }
            return position.ToString();
        }



    }
}

FizzBuzz/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Models.UserInput

<h2>Aviva FizzBuzz</h2>

<p>
    @using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Get))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Enter Number</h4>
            <hr />
            @Html.ValidationSummary(true, "")
            <div class="form-group">
                @Html.LabelFor(model => model.UserEntry)
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserEntry, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserEntry, "")
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Enter" />
           </div>
        </div>
    }
</p>

FizzBuzz/Views/FizzBuzz/Results.cshtml
@model IEnumerable<FizzBuzz.Models.FizzBuzzResult>

@{
    ViewBag.Title = "title";
}

<h2>FizzBuzz Results</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FizzBuzzRes)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <font color=@item.FontColor>
                    @Html.DisplayFor(modelItem => item.FizzBuzzRes)
                </font>
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("Back to Entry", "Index")
</div>